version: '3.9'
services:
  app:    
    image: node:lts-buster    
    container_name: app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"
    working_dir: ${ABSOLUTE_PATH_IN_CONTAINER}
    environment:
      - DEBUG=${DEBUG}
      - ABSOLUTE_PATH_IN_CONTAINER=${ABSOLUTE_PATH_IN_CONTAINER}
    volumes:
      - "./:${ABSOLUTE_PATH_IN_CONTAINER}"